compile:
        g++ calculate.cpp -o calculate.out
# This command will run the Hello World Program
run:
        ./calculate.out
#This command will "clean"  out the directory of any output files
clean:  
        rm *.out
~                                                                               
~                                                                               
~                                                                               
~                                                                               
~                                                                               
~                                                                               
~                                                                               
~                                                                               
~                                                                               
~                                                                               
~                                                                               
~                                                                               
~                                                                               
~                                                                               
~                                                                               
                                                              1,1           All
