//Rob Hughes                                                                                                           
//Project 2                                                                                                            
//Simulation Class Header                                                                                              

#ifndef SIM_H
#define SIM_H

#include <fstream>
#include <iomanip>
#include <iostream>
#include <string>

using namespace std;


class Simulation{

 private:

  int tort;
  int hare;
  string postitions[70];

 public:

  void moveTortoise(unsigned int *ptrTurtle);

  void moveHare(unsigned int *ptrHare);

  void runOneGame();

};
#endif
